name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          # Đường dẫn cần cache, vd dưới đây xài npm
          path: ~/.npm
          # Dùng để lấy cache về, vd dưới đây xài npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      # vào trong step -> id của phần cần lấy(ở đây là publish) -> outputs -> tên file (ở đây là script-file)
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          # Đường dẫn cần cache, vd dưới đây xài npm
          path: ~/.npm
          # Dùng để lấy cache về, vd dưới đây xài npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Public JS filename
        id: publish
        # Lưu ý, scripe-file là tên mà người dùng tùy chọn, và sẽ được sử dụng trong phần script-file trong outputs
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist files
          # Vị trí file cần lưu trỡ
          path: dist
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
      # Tải các artifact, cần phải chạy lần lượt các job thì mới có artiifact để tải
        uses: actions/download-artifact@v3
        with:
          # Xác định arifacts muốn tải
          name: dist files
      - name: Output contents
        run: ls
      - name: Output filename
          # Cần needs( ở đây là build) -> outputs -> tên file cần lấy
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
